//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.07 at 11:20:14 AM CEST 
//


package fr.cls.atoll.motu.api.message.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.cls.atoll.motu.api.message.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.cls.atoll.motu.api.message.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TimeCoverage }
     * 
     */
    public TimeCoverage createTimeCoverage() {
        return new TimeCoverage();
    }

    /**
     * Create an instance of {@link Axis }
     * 
     */
    public Axis createAxis() {
        return new Axis();
    }

    /**
     * Create an instance of {@link Attrs }
     * 
     */
    public Attrs createAttrs() {
        return new Attrs();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link RequestSize }
     * 
     */
    public RequestSize createRequestSize() {
        return new RequestSize();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link StatusModeResponse }
     * 
     */
    public StatusModeResponse createStatusModeResponse() {
        return new StatusModeResponse();
    }

    /**
     * Create an instance of {@link DataGeospatialCoverage }
     * 
     */
    public DataGeospatialCoverage createDataGeospatialCoverage() {
        return new DataGeospatialCoverage();
    }

    /**
     * Create an instance of {@link Variables }
     * 
     */
    public Variables createVariables() {
        return new Variables();
    }

    /**
     * Create an instance of {@link VariablesVocabulary }
     * 
     */
    public VariablesVocabulary createVariablesVocabulary() {
        return new VariablesVocabulary();
    }

    /**
     * Create an instance of {@link VariableVocabulary }
     * 
     */
    public VariableVocabulary createVariableVocabulary() {
        return new VariableVocabulary();
    }

    /**
     * Create an instance of {@link Attr }
     * 
     */
    public Attr createAttr() {
        return new Attr();
    }

    /**
     * Create an instance of {@link Variable }
     * 
     */
    public Variable createVariable() {
        return new Variable();
    }

    /**
     * Create an instance of {@link GeospatialCoverage }
     * 
     */
    public GeospatialCoverage createGeospatialCoverage() {
        return new GeospatialCoverage();
    }

    /**
     * Create an instance of {@link AvailableTimes }
     * 
     */
    public AvailableTimes createAvailableTimes() {
        return new AvailableTimes();
    }

    /**
     * Create an instance of {@link ProductMetadataInfo }
     * 
     */
    public ProductMetadataInfo createProductMetadataInfo() {
        return new ProductMetadataInfo();
    }

    /**
     * Create an instance of {@link AvailableDepths }
     * 
     */
    public AvailableDepths createAvailableDepths() {
        return new AvailableDepths();
    }

    /**
     * Create an instance of {@link StatusWPS }
     * 
     */
    public StatusWPS createStatusWPS() {
        return new StatusWPS();
    }

}
