//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// vhudson-jaxb-3268
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2007.12.21 at 08:38:29 AM CET
//

package fr.cls.atoll.motu.opendap.server;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * <p>
 * Java class for DataType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 *  &lt;simpleType name=&quot;DataType&quot;&gt;
 *    &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}token&quot;&gt;
 *      &lt;enumeration value=&quot;Grid&quot;/&gt;
 *      &lt;enumeration value=&quot;Image&quot;/&gt;
 *      &lt;enumeration value=&quot;Station&quot;/&gt;
 *      &lt;enumeration value=&quot;GIF&quot;/&gt;
 *      &lt;enumeration value=&quot;Unknown&quot;/&gt;
 *    &lt;/restriction&gt;
 *  &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlEnum
public enum DataType {

    GIF("GIF"), @XmlEnumValue("Grid")
    GRID("Grid"), @XmlEnumValue("Image")
    IMAGE("Image"), @XmlEnumValue("Station")
    STATION("Station"), @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    DataType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataType fromValue(String v) {
        for (DataType c : DataType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
