//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3268 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.21 at 08:38:29 AM CET 
//

package fr.cls.atoll.motu.opendap.server;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for fileScan element declaration.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 *  &lt;element name=&quot;fileScan&quot;&gt;
 *    &lt;complexType&gt;
 *      &lt;complexContent&gt;
 *        &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *          &lt;attribute name=&quot;dirPath&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}anySimpleType&quot; /&gt;
 *          &lt;attribute name=&quot;scanMinutes&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}anySimpleType&quot; /&gt;
 *        &lt;/restriction&gt;
 *      &lt;/complexContent&gt;
 *    &lt;/complexType&gt;
 *  &lt;/element&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "fileScan")
public class FileScan {

    @XmlAttribute(required = true)
    protected String dirPath;
    @XmlAttribute
    protected String scanMinutes;

    /**
     * Gets the value of the dirPath property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDirPath() {
        return dirPath;
    }

    /**
     * Sets the value of the dirPath property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDirPath(String value) {
        this.dirPath = value;
    }

    /**
     * Gets the value of the scanMinutes property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getScanMinutes() {
        return scanMinutes;
    }

    /**
     * Sets the value of the scanMinutes property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setScanMinutes(String value) {
        this.scanMinutes = value;
    }

}
