//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.05 at 12:55:04 PM CEST 
//


package fr.cls.atoll.motu.processor.opengis.wps100;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.cls.atoll.motu.processor.opengis.wps100 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.cls.atoll.motu.processor.opengis.wps100
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComplexDataCombinationType }
     * 
     */
    public ComplexDataCombinationType createComplexDataCombinationType() {
        return new ComplexDataCombinationType();
    }

    /**
     * Create an instance of {@link SupportedUOMsType.Default }
     * 
     */
    public SupportedUOMsType.Default createSupportedUOMsTypeDefault() {
        return new SupportedUOMsType.Default();
    }

    /**
     * Create an instance of {@link WSDL }
     * 
     */
    public WSDL createWSDL() {
        return new WSDL();
    }

    /**
     * Create an instance of {@link ProcessDescriptionType.ProcessOutputs }
     * 
     */
    public ProcessDescriptionType.ProcessOutputs createProcessDescriptionTypeProcessOutputs() {
        return new ProcessDescriptionType.ProcessOutputs();
    }

    /**
     * Create an instance of {@link LiteralOutputType }
     * 
     */
    public LiteralOutputType createLiteralOutputType() {
        return new LiteralOutputType();
    }

    /**
     * Create an instance of {@link ResponseBaseType }
     * 
     */
    public ResponseBaseType createResponseBaseType() {
        return new ResponseBaseType();
    }

    /**
     * Create an instance of {@link SupportedCRSsType }
     * 
     */
    public SupportedCRSsType createSupportedCRSsType() {
        return new SupportedCRSsType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link ValuesReferenceType }
     * 
     */
    public ValuesReferenceType createValuesReferenceType() {
        return new ValuesReferenceType();
    }

    /**
     * Create an instance of {@link InputDescriptionType }
     * 
     */
    public InputDescriptionType createInputDescriptionType() {
        return new InputDescriptionType();
    }

    /**
     * Create an instance of {@link CRSsType }
     * 
     */
    public CRSsType createCRSsType() {
        return new CRSsType();
    }

    /**
     * Create an instance of {@link ComplexDataDescriptionType }
     * 
     */
    public ComplexDataDescriptionType createComplexDataDescriptionType() {
        return new ComplexDataDescriptionType();
    }

    /**
     * Create an instance of {@link ProcessDescriptionType }
     * 
     */
    public ProcessDescriptionType createProcessDescriptionType() {
        return new ProcessDescriptionType();
    }

    /**
     * Create an instance of {@link LiteralInputType }
     * 
     */
    public LiteralInputType createLiteralInputType() {
        return new LiteralInputType();
    }

    /**
     * Create an instance of {@link ProcessBriefType }
     * 
     */
    public ProcessBriefType createProcessBriefType() {
        return new ProcessBriefType();
    }

    /**
     * Create an instance of {@link UOMsType }
     * 
     */
    public UOMsType createUOMsType() {
        return new UOMsType();
    }

    /**
     * Create an instance of {@link SupportedComplexDataType }
     * 
     */
    public SupportedComplexDataType createSupportedComplexDataType() {
        return new SupportedComplexDataType();
    }

    /**
     * Create an instance of {@link SupportedCRSsType.Default }
     * 
     */
    public SupportedCRSsType.Default createSupportedCRSsTypeDefault() {
        return new SupportedCRSsType.Default();
    }

    /**
     * Create an instance of {@link ProcessDescriptionType.DataInputs }
     * 
     */
    public ProcessDescriptionType.DataInputs createProcessDescriptionTypeDataInputs() {
        return new ProcessDescriptionType.DataInputs();
    }

    /**
     * Create an instance of {@link SupportedComplexDataInputType }
     * 
     */
    public SupportedComplexDataInputType createSupportedComplexDataInputType() {
        return new SupportedComplexDataInputType();
    }

    /**
     * Create an instance of {@link ProcessDescriptions }
     * 
     */
    public ProcessDescriptions createProcessDescriptions() {
        return new ProcessDescriptions();
    }

    /**
     * Create an instance of {@link SupportedUOMsType }
     * 
     */
    public SupportedUOMsType createSupportedUOMsType() {
        return new SupportedUOMsType();
    }

    /**
     * Create an instance of {@link OutputDescriptionType }
     * 
     */
    public OutputDescriptionType createOutputDescriptionType() {
        return new OutputDescriptionType();
    }

    /**
     * Create an instance of {@link ComplexDataCombinationsType }
     * 
     */
    public ComplexDataCombinationsType createComplexDataCombinationsType() {
        return new ComplexDataCombinationsType();
    }

}
