package fr.cls.atoll.motu.web.bll.catalog.product.cache;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import fr.cls.atoll.motu.web.dal.request.netcdf.data.Product;

/**
 * This cache is used to speed up the retrieve of a product in the catalog It indexes all products by a
 * concatenation of the configService name and the product id <br>
 * <br>
 * Copyright : Copyright (c) 2016 <br>
 * <br>
 * Société : CLS (Collecte Localisation Satellites)
 * 
 * @author Pierre LACOSTE
 * @version $Revision: 1.1 $ - $Date: 2007-05-22 16:56:28 $
 */
public class ProductCache implements IProductCache {

    /**
     * Key is generated by method {@link #getMapKey(String, String)} from the configServiceName and the
     * productId
     */
    private Map<String, Product> productsMap;

    public ProductCache() {
        productsMap = Collections.synchronizedMap(new HashMap<String, Product>());
    }

    @Override
    public Product getProduct(String configServiceName, String productId) {
        return productsMap.get(getMapKey(configServiceName, productId));
    }

    @Override
    public void setProduct(String configServiceName, Product product) {
        Product pInList = getProduct(configServiceName, product.getProductId());
        if (pInList != null) {
            productsMap.remove(getMapKey(configServiceName, product.getProductId()));
        }
        productsMap.put(getMapKey(configServiceName, product.getProductId()), product);
    }

    public String getMapKey(String configServiceName, String productId) {
        return new String(configServiceName + "@" + productId).toUpperCase();
    }

}
