//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3268 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.20 at 01:07:55 PM CET 
//


package fr.cls.atoll.motu.tds.server;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0}DatasetType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0}fmrcInventory" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="runsOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fmrcInventory"
})
public class DatasetFmrc
    extends DatasetType
{

    @XmlElement(namespace = "http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0")
    protected FmrcInventory fmrcInventory;
    @XmlAttribute(required = true)
    protected String path;
    @XmlAttribute
    protected Boolean runsOnly;

    /**
     * Gets the value of the fmrcInventory property.
     * 
     * @return
     *     possible object is
     *     {@link FmrcInventory }
     *     
     */
    public FmrcInventory getFmrcInventory() {
        return fmrcInventory;
    }

    /**
     * Sets the value of the fmrcInventory property.
     * 
     * @param value
     *     allowed object is
     *     {@link FmrcInventory }
     *     
     */
    public void setFmrcInventory(FmrcInventory value) {
        this.fmrcInventory = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the runsOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRunsOnly() {
        return runsOnly;
    }

    /**
     * Sets the value of the runsOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRunsOnly(Boolean value) {
        this.runsOnly = value;
    }

}
