//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3268 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.20 at 01:07:55 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0")
package fr.cls.atoll.motu.tds.server;
