//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3268 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.02 at 10:55:41 AM CEST 
//

package fr.cls.atoll.motu.msg.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * <p>
 * Java class for statusModeType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name=&quot;statusModeType&quot;&gt;
 *   &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}unsignedShort&quot;&gt;
 *     &lt;enumeration value=&quot;0&quot;/&gt;
 *     &lt;enumeration value=&quot;1&quot;/&gt;
 *     &lt;enumeration value=&quot;2&quot;/&gt;
 *     &lt;enumeration value=&quot;3&quot;/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlEnum(Integer.class)
public enum StatusModeType {

    @XmlEnumValue("1")
    DONE(1), @XmlEnumValue("2")
    ERROR(2), @XmlEnumValue("0")
    INPROGRESS(0), @XmlEnumValue("3")
    PENDING(3);
    private final int value;

    StatusModeType(int v) {
        value = v;
    }

    public int value() {
        return value;
    }

    public static StatusModeType fromValue(int v) {
        for (StatusModeType c : StatusModeType.values()) {
            if (c.value == v) {
                return c;
            }
        }
        throw new IllegalArgumentException(String.valueOf(v));
    }

    public static StatusModeType fromValue(String v) {
        for (StatusModeType c : StatusModeType.values()) {
            if (c.toString().equalsIgnoreCase(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(String.valueOf(v));
    }
}
